name:                wait-on-port
version:             0.1.0.0
github:              "githubuser/wait-on-port"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description: A single function library which attempts to connect a port over and over again until it accepts a connection.

default-extensions:
- ScopedTypeVariables
- RecordWildCards
- LambdaCase

dependencies:
- base >= 4.7 && < 5
- network

library:
  source-dirs: src

tests:
  unit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wait-on-port
    - hspec
    - stm
