name:                port-utils
version:             0.1.0.3
github: jfischoff/port-utils
license:             BSD3
author:              "Jonathan Fischoff"
maintainer:          "jonathangfischoff@gmail.com"
copyright:           "2018 Jonathan Fischoff"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Utilities for creating and waiting on ports
description: Utilities for creating and waiting on ports.
 .
 @openFreePort@ will create a socket bound to a random port (like @warp@'s @openFreePort@).
 .
 @wait@ will attempt to connect to given host and port repeatedly until successful.
 .

default-extensions:
- ScopedTypeVariables
- RecordWildCards
- LambdaCase

dependencies:
- base >= 4.7 && < 5
- network

library:
  source-dirs: src

tests:
  unit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - hspec
    - stm
    - port-utils
